#' Exif Data
#'
#' Exif data of a specific photograph
#' 
#' @param api_key Your API key generated by your Flickr developper account
#' @param photo_id Specific characters/numbers of photo id of which you would like to get information
#' 
#' @author Koki Ando <koki.25.ando@gmail.com>
#'
#' @import RCurl
#' @import jsonlite
#' 
#' @return This function returns a dataframe of Exif information of given photograph
#' 
#' @example
#' \dontrun{
#'   getExif(api_key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, photo_id="45961963324")
#' }
#'
#' @export

getExif <- function(api_key, photo_id){
  url <- paste0("https://api.flickr.com/services/rest/?method=flickr.photos.getExif&api_key=", api_key, "&photo_id=",
         photo_id, "&format=json&nojsoncallback=1")
  raw_data <- RCurl::getURL(url, ssl.verifypeer = FALSE)
  data <- jsonlite::fromJSON(raw_data)
  as.data.frame(data)
}
