#' Specific Geolocation of Given Photograph
#' 
#' Datafram of Geolocation data of given photographs 
#' 
#' @param api_key Your API key generated by your Flickr developper account
#' @param photo_id Specific characters/numbers of photo id of which you would like to get information
#' 
#' @author Koki Ando <koki.25.ando@gmail.com>
#' 
#' @import RCurl
#' @import stringr
#' @import tidyr
#' @import magrittr
#' @import jsonlite
#' 
#' @return This function return a datafram of given photo id
#' 
#' @exmaple
#' \dontrun{
#'   getPhotoLocation(api_key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", photo_id = "45961963324")
#' }
#' 
#' @export

getPhotoLocation <- function(api_key, photo_id){
  head_url = "https://api.flickr.com/services/rest/?method=flickr.photos.geo.getLocation&api_key="
  url = paste0(head_url, api_key,
               "&photo_id=", photo_id, "&format=json&nojsoncallback=1")
  raw_data <- RCurl::getURL(url, ssl.verifypeer = FALSE)
  data <- jsonlite::fromJSON(raw_data)
  df <- as.data.frame(data) %>% 
    tidyr::gather(key="Type", value="Value")
  df$Type <- stringr::str_remove(df$Type, "photo.location.")
  df
}