#' Photo's information
#'
#' Data of photos posted by specific Flickr account.
#' 
#' @param api_key Your API key generated by your Flickr developper account
#' @param user_id Specific string of user id of which you would like to get information
#' 
#' @author Koki Ando <koki.25.ando@gmail.com>
#' 
#' @import RCurl
#' @import jsonlite
#' @import stringr
#' 
#' @return This function return \code{data.frame} including columns:
#' \itemize{
#'  \item id
#'  \item owner
#'  \item secret
#'  \item server
#'  \item farm
#'  \item title
#'  \item ispublic
#'  \item isfriend
#'  \item isfamily
#' }
#' 
#' @examples
#' \dontrun{
#'   getPhotos(api_key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", user_id="141696738@N08")
#' }
#' 
#' @export 


getPhotos <- function(api_key, user_id){
  url = paste0("https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=", api_key,
               "&user_id=", stringr::str_replace(user_id, "@", "%40"), "&format=json&nojsoncallback=1")
  raw_data <- RCurl::getURL(url, ssl.verifypeer = FALSE)
  data <- jsonlite::fromJSON(raw_data)
  as.data.frame(data$photos$photo)
}

getPhotos(api_key=api_key, user_id="141696738@N08")
